apiVersion: v1
kind: Secret
metadata:
  name: sandbox-secrets
  namespace: devops-sandbox
type: Opaque
stringData:
  POSTGRES_USER: sandboxuser
  POSTGRES_PASSWORD: changeme_strong_password
  POSTGRES_DB: sandboxdb
  PGADMIN_EMAIL: admin@sandbox.local
  PGADMIN_PASSWORD: changeme_pgadmin_password
