apiVersion: v1
kind: Secret
metadata:
  name: sandbox-secrets
  namespace: devops-sandbox
type: Opaque
stringData:
  POSTGRES_USER: sandboxnitim
  POSTGRES_PASSWORD: solidnapasswordlolol12345
  POSTGRES_DB: sandboxdb
  PGADMIN_EMAIL: czartimothyvinson@gmail.com
  PGADMIN_PASSWORD: adminpasswordnitim
